######################################################################
# Automatically generated by qmake (3.0) Tue Aug 8 14:19:53 2017
######################################################################

TEMPLATE = app
TARGET = NaturalPhenomena
INCLUDEPATH += . /opt/local/include

QT += widgets opengl gui 

LIBS += -lGLU

QMAKE_CXXFLAGS += -std=c++11

# Input
HEADERS += Window.h Widget.h Sky.h
SOURCES += main.cpp \
		   Window.cpp \
           Widget.cpp \
		   Sky.cpp
